### PR TITLE
new: Add a `No Default` option when running the `configure` command

### PR DESCRIPTION
**Pull request by lgarber-akamai**
## 📝 Description

This change adds a `No Default` option to the `linode-cli configure` command that allows users to optionally clear a default if it is already defined in the existing config. This differs from the skip (enter) functionality in that the skip functionality retains the previous config value and the `No Default` option drops the config value.

## ✔️ How to Test

`make testunit`

### CODE REVIEW

**Review by ezilber-akamai — APPROVED** [review]
LGTM!

**Review by yec-akamai — COMMENTED** [review]
Code looks good! However, when I was testing locally, there isn't a `No default` option popping up for `postgresql`, even though i set its default value in a previous configure. Others work well. I can't tell why this value is different. Do you have any idea on it?

**Comment by lgarber-akamai** [comment]
> Code looks good! However, when I was testing locally, there isn't a `No default` option popping up for `postgresql`, even though i set its default value in a previous configure. Others work well. I can't tell why this value is different. Do you have any idea on it?

Let me take a look :eyes:

**Comment by lgarber-akamai** [comment]
> Code looks good! However, when I was testing locally, there isn't a `No default` option popping up for `postgresql`, even though i set its default value in a previous configure. Others work well. I can't tell why this value is different. Do you have any idea on it?

Ah okay, looks like it was just a typo. Could you test this again with the latest commit @yec-akamai ?

**Comment by yec-akamai** [comment]
> > Code looks good! However, when I was testing locally, there isn't a `No default` option popping up for `postgresql`, even though i set its default value in a previous configure. Others work well. I can't tell why this value is different. Do you have any idea on it?
> 
> Ah okay, looks like it was just a typo. Could you test this again with the latest commit @yec-akamai ?

Works now! Thank you

**Review by yec-akamai — APPROVED** [review]

**Pull request merged**
