### PR TITLE
setup: fix required deps mismatch

### PR DESCRIPTION
**Pull request by chenrui333**
## 📝 Description

Fix missing packaging dependency in the setup.py file

relates to https://github.com/Homebrew/homebrew-core/pull/126192

## ✔️ How to Test

Tested out in the homebrew CI.

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @lgarber-akamai @zliang-akamai

**Review by lgarber-akamai — APPROVED** [review]
Thanks for the contribution!
Generally it is best practice to keep `requirements.txt` and `install_requires` separate, but since we don't pin versions in `requirements.txt` this change should be fine 👍 

Just a note, [a patch for this issue](https://github.com/linode/linode-cli/pull/413) has been merged into the `main` branch and we have a [PR up](https://github.com/linode/linode-cli/pull/415) to merge it back into the `dev` branch. We'll need to merge that change first to keep our git history consistent, so I'll let you know if we need you to resolve any merge conflicts.

**Comment by chenrui333** [comment]
I think this is a better fix of managing deps in two places.

**Comment by zliang-akamai** [comment]
> I think this is a better fix of managing deps in two places.

Yeah, I think that's a good way to manage dependencies. We are going to get the patch in `main` merged back to `dev` then we will be merging this PR.

**Review by zliang-akamai — APPROVED** [review]

**Review by lgarber-akamai — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks folks!!

**Comment by chenrui333** [comment]
this approach actually does not quite work as there is requirements.txt in the pypi artifact, either we bundle requirements.txt or we need to revert this change.

**Comment by chenrui333** [comment]
created a patch for such issue (I should really tested before :) )

**Pull request merged**
