### PR TITLE
Mention Homebrew installation option in the README

### PR DESCRIPTION
**Pull request by tangestani**
I added linode-cli to the Homebrew package manager: Homebrew/homebrew-core#93251

Edited the README to mention that as an installation option.

### CODE REVIEW

**Comment by Dorthu** [comment]
Thank you for adding the CLI to Homebrew - that's very exciting.  

I'm going to bring this up internally and see how we want to go about endorsing third party distributions of the CLI, as right now the only official distribution channel that we support is installation via pip, and we would likely want to include other endorsed distribution methods in our test plan for new releases to ensure future releases don't cause issues for them.

**Comment by Dorthu** [comment]
After discussing this with the team, it was clear that we absolutely do want to support and feature third party distributions of the CLI.  However, we don't have the resources on this project to commit to testing that each release works through alternate distribution platforms.  How do you feel about moving these notes to a "Community Distributions" section with a note that these distributions are not officially supported and tested with each release?  If you're alright with that, I can make the changes to make it happy.

**Comment by tangestani** [comment]
Sounds good to me. Maybe we can revisit it having it be officially supported in the future.

**Comment by Dorthu** [comment]
Supporting other distribution channels is on our list, but I can't make any promising as to when it might happen.

**Pull request merged**
