### PR TITLE
test: Remove unnecessary assertion warnings and update exit codes in tests 

### PR DESCRIPTION
**Pull request by ykim-1**
## 📝 Description

Removing assertion warnings for cleaner output while running integration tests
```
linode-cli/tests/integration/kernels/test_kernels.py:62:
linode-cli/tests/integration/kernels/test_kernels.py:66:
linode-cli/tests/integration/kernels/test_kernels.py:31: 
linode-cli/tests/integration/kernels/test_kernels.py:15: 
linode-cli/tests/integration/linodes/test_power_status.py:68:
linode-cli/tests/integration/domains/test_domain_records.py:159: 
linode-cli/tests/integration/domains/test_domain_records.py:135:
linode-cli/tests/integration/domains/test_domain_records.py:115: 
linode-cli/tests/integration/domains/test_domain_records.py:85: 
PytestAssertRewriteWarning: assertion is always true, perhaps remove parentheses?
```

Also as part of this PR, I updated exit codes to reflect [latest changes in exit codes](https://github.com/linode/linode-cli/pull/622/)
 
## ✔️ How to Test
Ensure latest linode-cli dev branch is used to install when running tests
`make TEST_CASE="test_shutdown_linode -s" testint`
`make MODULE="kernels" testint `
`make MODULE="domains" testint`
`make MODULE="linodes" testint`
`make MODULE="firewalls" testint`
`make MODULE="nodebalancers" testint`
`make MODULE="stackscripts" testint`
`make MODULE="tags" testint`
`make MODULE="vpc" testint`
`make MODULE="volumes" testint`

## 📷 Preview

**If applicable, include a screenshot or code snippet of this change. Otherwise, please remove this section.**

### CODE REVIEW

**Review by ezilber-akamai — COMMENTED** [review]
I'm seeing some test failures when running `make MODULE="domains" testint`. The failures seem to be related to the new exit code enum that I added a while back, but I fixed the failing integration tests that were caused by this. Here's the errors I saw:

```
______________________________________________________ test_fail_to_create_master_domain_with_invalid_tags _______________________________________________________

    def test_fail_to_create_master_domain_with_invalid_tags():
        timestamp = str(time.time_ns())
        bad_tag = "*"
    
>       exec_failing_test_command(
            BASE_CMD
            + [
                "create",
                "--type",
                "master",
                "--domain",
                timestamp + "example.com",
                "--soa_email=" + timestamp + "pthiel@linode.com",
                "--text",
                "--no-header",
                "--format=id",
                "--tag",
                bad_tag,
            ]
        )

tests/integration/domains/test_domains_tags.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = ['linode-cli', 'domains', 'create', '--type', 'master', '--domain', ...], expected_code = <ExitCodes.REQUEST_FAILED: 2>

    def exec_failing_test_command(
        args: List[str], expected_code: int = ExitCodes.REQUEST_FAILED
    ):
        process = subprocess.run(args, stderr=subprocess.PIPE)
>       assert process.returncode == expected_code
E       AssertionError

tests/integration/helpers.py:47: AssertionError
_______________________________________________________ test_fail_to_create_slave_domain_with_invalid_tags _______________________________________________________

    def test_fail_to_create_slave_domain_with_invalid_tags():
        timestamp = str(time.time_ns())
        bad_tag = "*"
    
>       exec_failing_test_command(
            BASE_CMD
            + [
                "create",
                "--type",
                "slave",
                "--domain",
                timestamp + "example.com",
                "--soa_email=" + timestamp + "pthiel@linode.com",
                "--text",
                "--no-header",
                "--format=id",
                "--tag",
                bad_tag,
            ]
        )

tests/integration/domains/test_domains_tags.py:44: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = ['linode-cli', 'domains', 'create', '--type', 'slave', '--domain', ...], expected_code = <ExitCodes.REQUEST_FAILED: 2>

    def exec_failing_test_command(
        args: List[str], expected_code: int = ExitCodes.REQUEST_FAILED
    ):
        process = subprocess.run(args, stderr=subprocess.PIPE)
>       assert process.returncode == expected_code
E       AssertionError

tests/integration/helpers.py:47: AssertionError
_________________________________________________________ test_create_domain_fails_without_spcified_type _________________________________________________________

    def test_create_domain_fails_without_spcified_type():
        timestamp = str(time.time_ns())
    
        # get debug output from linode-cli to a temporary file..
        # not all output from the linode-cli goes to stdout, stderr
    
>       result = exec_failing_test_command(
            BASE_CMD
            + [
                "create",
                "--domain",
                "example.bc-" + timestamp + ".com",
                "--soa_email",
                "pthiel@linode.com",
                "--text",
                "--no-headers",
            ]
        ).stderr.decode()

tests/integration/domains/test_master_domains.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = ['linode-cli', 'domains', 'create', '--domain', 'example.bc-1723060547573861000.com', '--soa_email', ...], expected_code = <ExitCodes.REQUEST_FAILED: 2>

    def exec_failing_test_command(
        args: List[str], expected_code: int = ExitCodes.REQUEST_FAILED
    ):
        process = subprocess.run(args, stderr=subprocess.PIPE)
>       assert process.returncode == expected_code
E       AssertionError

tests/integration/helpers.py:47: AssertionError
_______________________________________________________ test_create_master_domain_fails_without_soa_email ________________________________________________________

    def test_create_master_domain_fails_without_soa_email():
        timestamp = str(time.time_ns())
>       result = exec_failing_test_command(
            BASE_CMD
            + [
                "create",
                "--type",
                "master",
                "--domain",
                "example.bc-" + timestamp + ".com",
                "--text",
                "--no-headers",
            ]
        ).stderr.decode()

tests/integration/domains/test_master_domains.py:70: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = ['linode-cli', 'domains', 'create', '--type', 'master', '--domain', ...], expected_code = <ExitCodes.REQUEST_FAILED: 2>

    def exec_failing_test_command(
        args: List[str], expected_code: int = ExitCodes.REQUEST_FAILED
    ):
        process = subprocess.run(args, stderr=subprocess.PIPE)
>       assert process.returncode == expected_code
E       AssertionError

tests/integration/helpers.py:47: AssertionError
```

Do you also see these failures locally?

**Comment by ykim-1** [comment]
https://github.com/linode/linode-cli/actions/runs/10307106424

**Review by ezilber-akamai — APPROVED** [review]
After running `make install` in the `dev` branch, all tests were passing. Nice work!

**Review by zliang-akamai — APPROVED** [review]
LGTM!

**Pull request merged**
