### PR TITLE
test: update all legacy compute regions in integration tests

### PR DESCRIPTION
**Pull request by ykim-1**
## 📝 Description

Regions have been updated:
Legacy Compute sites are in Atlanta, Dallas, Frankfurt, Fremont, London, Mumbai, Newark, Singapore, Sydney, Tokyo, and Toronto

New Core Compute sites are in Amsterdam, Chennai, Chicago, Jakarta, Los Angeles, Madrid (coming soon!), Miami, Milan, Osaka, Paris, São Paulo, Seattle, Stockholm, and Washington, DC (and the list will continue to grow).

All integration test runs provision infrastructure only in New Core Compute sites (not Legacy Compute sites). For this repository, replacing all legacy regions with Chicago and Miami region

## ✔️ How to Test

make testint 
Build - https://github.com/linode/linode-cli/actions/runs/7146447668

## 📷 Preview

**If applicable, include a screenshot or code snippet of this change. Otherwise, please remove this section.**

### CODE REVIEW

**Comment by yec-akamai** [comment]
The build https://github.com/linode/linode-cli/actions/runs/7146447668 seems failed. Is it related to API issue?

**Comment by ykim-1** [comment]
> The build https://github.com/linode/linode-cli/actions/runs/7146447668 seems failed. Is it related to API issue?

Seems like intermittent failures. I was able to get the local runs to pass

**Review by yec-akamai — APPROVED** [review]
Got it. LGTM!

**Review by amisiorek-akamai — APPROVED** [review]
Looks good (saw comment about occasional failures) 👍

**Pull request merged**
